name: "Build Container"
description: "Build Container"
inputs:
  aws_region:
    default: eu-west-1
    description: name of the aws region to deploy to
    required: false
  aws_role:
    description: name of the role to use
    required: true
  ecr_repo:
    description: name of the ecr repository
    required: true
  docker_context:
    description: name of the folder where the Dockerfile lives
    required: true
  sha_tag:
    description: sha tag
    required: true
  version_tag:
    description: version tag
    required: true
  branch_tag:
    description: branch tag
    required: true
  push_image:
    description: push the image to ecr
    required: false
    default: true
runs:
  using: "composite"
  steps:
    # Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ${{ inputs.aws_region }}
        role-to-assume: arn:aws:iam::289334807197:role/github-actions-oidc-GitHubActionsServiceRole-6CE9XOJGN8I8
        role-session-name: OIDCSession
        mask-aws-account-id: false
    # Login to ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and push
      uses: docker/build-push-action@v4
      env:
        ECR_REGISTRY: 289334807197.dkr.ecr.eu-west-1.amazonaws.com
        ECR_REPOSITORY: ${{ inputs.ecr_repo }}
        SHA_TAG: ${{ inputs.sha_tag }}
        VERSION_SHA_TAG: "${{ inputs.version_tag }}-${{ inputs.sha_tag }}"
        VERSION_TAG: ${{ inputs.version_tag }}
        BRANCH_TAG: ${{ inputs.branch_tag }}
      with:
        context: "${{ inputs.docker_context }}"
        push: ${{ inputs.push_image }}
        tags: |
          $ECR_REGISTRY/$ECR_REPOSITORY:$SHA_TAG
          $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION_TAG
          $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH_TAG
        labels:
          org.opencontainers.image.revision=$SHA_TAG
          org.opencontainers.image.source="$ECR_REGISTRY/$ECR_REPOSITORY
          org.opencontainers.image.version=$VERSION_TAG
          org.opencontainers.image.created=$(date +'%m/%d/%Y')