name: Bump Version
description: "Bump Version"

outputs:
  version:
    description: "Version from package.json"
    value: ${{ steps.package-version.outputs.current-version }}

runs:
  using: "composite"
  steps:
    - name: ❔ get-npm-version ❔
      id: bump_version
      shell: bash
      run: |
        #!/bin/bash
        set -x
        npm version prerelease --preid=develop
