name: "Build NodeJs container"
description: "Build NodeJs container"
inputs:
  aws_region:
    default: eu-west-1
    description: name of the aws region to deploy to
    required: false
  node_version_tag:
    description: Version of node to use
    required: false
    default: 16.20.0-alpine
  command:
    description: 'The command to execute for build and test.'
    required: true
runs:
  using: "composite"
  steps:
    - name: Branch to Build
      shell: bash
      run: echo -e "🔧 Following branch will be build ${{ github.ref }} 🔧"
    # Checkout code
    - name: ✅ Checkout ✅
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    
    - name: Prepare
      shell: bash
      run: |
        npm install -g npm
        npm cache clean --force
        npm install

    - name: Build & Test
      shell: bash
      run: ${{ inputs.command }}

    # Create Output Cache
    - name: 📺 Set Outputs 📺
      id: outputs
      shell: bash
      env:
        SHA_TAG: ${{ github.sha }}
        BRANCH_TAG: ${{ github.ref_name }}
      run: |
        echo "sha_tag=${{ env.SHA_TAG }}" >> $GITHUB_OUTPUT
        echo "branch_tag=${{ env.BRANCH_TAG }}" >> $GITHUB_OUTPUT

outputs:
  sha_tag:
    description: "The SHA tag"
    value: ${{ steps.outputs.outputs.sha_tag }}
  branch_tag:
    description: "The branch tag"
    value: ${{ steps.outputs.outputs.branch_tag }}
