name: 🏗️ Build

on:
  workflow_dispatch:

env:
  BRANCH: ${{ github.ref_name}}

run-name: 🏗️ Build ${{ github.ref_name	}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ✅ Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.VENLY_GITHUB_ACTIONS_TOKEN }}

      - name: 🔍 Get Version
        uses: ./.github/actions/get_version

      - name: ⬆️ Bump Version
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' && (startsWith(github.ref, 'refs/heads/develop') || startsWith(github.ref, 'refs/heads/hotfix-') || startsWith(github.ref, 'refs/heads/release-'))
        uses: ./.github/actions/bump_version
        with:
          token: ${{ secrets.VENLY_GITHUB_ACTIONS_TOKEN }}

      - name: 🛠️ Setup Node.js 16.x
        uses: actions/setup-node@v3
        id: node_setup
        with:
          node-version: 16.x

      - name: 🏗️ Build Node
        run: |
          #!/bin/bash
          set -x
          npm i
          npm run build

      - name: 🚀 Publish Npm
        uses: ./.github/actions/publish_npm
        with:
          npm_token: ${{ secrets.NPM_KEY }}
          token: ${{ secrets.VENLY_GITHUB_ACTIONS_TOKEN }}

      - name: 🔄 Merge Back
        if: (startsWith(github.ref, 'refs/heads/hotfix-') || startsWith(github.ref, 'refs/heads/release-'))
        uses: ./.github/actions/merge_back
        with:
          branch: ${{ github.ref_name }}
          token: ${{ secrets.VENLY_GITHUB_ACTIONS_TOKEN }}
