name: 🏗️ Build
on:
  push:
    paths-ignore:
      - .github/**
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  AWS_REGION: "eu-west-1"
permissions:
  actions: read
  checks: write
  contents: write
  deployments: read
  id-token: write
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
run-name: 🏗️ Build ${{ github.ref_name	}}
jobs:
  # =====================================================
  # Job: Build
  # =====================================================
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [18, 20]
      fail-fast: false
    steps:
      - name: ✅ Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: get_version
        uses: .github/actions/get_version

      - name: bump_version
        if: github.event_name == 'push' && (startsWith(github.ref, 'refs/heads/develop') || startsWith(github.ref, 'refs/heads/hotfix-') || startsWith(github.ref, 'refs/heads/release-'))
        uses: .github/actions/bump_version

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        id: node_setup
        with:
          node-version: ${{ matrix.node_version }}

      - name: Set up .npmrc
        run: |
          echo "//registry.npmjs.org/:_authToken=\${{ secrets.NPM_KEY }}" > .npmrc
        env:
          NPM_KEY: ${{ secrets.NPM_KEY }}

      - name: Build
        id: build_node
        uses: .github/actions/build_node
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          node_version: ${{ matrix.node_version }}
          commands: |
            npm install
            npm run build

      - name: Publish to npm
        run: |
          if [ "${{ github.ref }}" == "refs/heads/master" ]; then
            npm publish
          else
            npm publish --tag $(echo "${{ github.ref }}" | sed 's|refs/heads/||')
          fi

  # =====================================================
  # Job: Merge Back
  # =====================================================
  merge-back:
    if: startsWith(github.ref, 'refs/heads/hotfix-') || startsWith(github.ref, 'refs/heads/release-')
    runs-on: ubuntu-latest
    outputs:
      runner_name: ${{ runner.name }}
    steps:
      - name: ✅ Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.VENLY_GITHUB_ACTIONS_TOKEN }}

      - name: Merge Back To Develop
        id: merge_back
        uses: ArkaneNetwork/venly-github-workflows/.github/actions/merge_back@main
        with:
          branch: ${{ github.ref }}
          token: ${{ secrets.VENLY_GITHUB_ACTIONS_TOKEN }}
