name: Deploy
on:
  workflow_dispatch:
    inputs:
      branch_name:
        type: string
        description: "Branch to deploy"
        required: true
      environment:
        type: choice
        description: "Environment to deploy to AWS CloudFormation"
        required: true
        default: "qa"
        options:
          - prd
          - qa
          - sandbox
          - staging
          - dev
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    branches:
      - develop
env:
  AWS_REGION: "eu-west-1"
jobs:
  deploy:
    strategy:
      matrix:
        microservice: 
          - connect-v2
        ecr:
          - venly-connectv2-eu-west-1
        include:
        - service: connect-v2
          ecr: venly-connectv2-eu-west-1
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Github Event
        id: event
        run: |
          echo "Event that caused the deploy: ${{ github.event_name}}"
      - name: Deploy Application
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: ./.github/actions/ecs_deploy
        with:
          aws_region: ${{ env.AWS_REGION }}
          aws_role: ${{ secrets.NONPRD_DEPLOY_ROLE }}
          cluster_name: connect-${{ inputs.environment }}-cluster
          ecr_repo: ${{ matrix.ecr }}
          environment: ${{ inputs.environment }}
          service_name: ${{ matrix.microservice }}
          tag_to_deploy: VLDEVOPS-135-update-ecs-deploys
          token: ${{ secrets.VENLY_GITHUB_ACTIONS_TOKEN }}
  # deploy-qa:
  #   runs-on: ubuntu
  #   permissions:
  #     id-token: write
  #     contents: write
  #   steps:
  #     - name: Deploy Application
  #       if: github.event_name == 'workflow_run' && github.event.workflow_run.head_branch == 'develop'
  #       uses: ArkaneNetwork/venly-github-workflows/.github/actions/ecs_deploy@main
  #       with:
  #         aws_region: ${{ env.AWS_REGION }}
  #         aws_role: ${{ secrets.NONPRD_DEPLOY_ROLE }}
  #         branch_name: develop
  #         container_name: wallet-connect
  #         cluster_name: wallet-connect-qa-cluster
  #         service_name: wallet-connect-qa-service-fargate
  #         spring_application_name: wallet-connect-qa
  #         tag_to_use: version
  #         token: ${{ secrets.VENLY_GITHUB_ACTIONS_TOKEN }}
  # deploy:
  #   runs-on: ubuntu
  #   permissions:
  #     id-token: write
  #     contents: write
  #   steps:
  #     - name: Deploy Application
  #       if: github.event_name == 'workflow_dispatch'
  #       uses: ArkaneNetwork/venly-github-workflows/.github/actions/ecs_deploy@main
  #       with:
  #         aws_region: ${{ env.AWS_REGION }}
  #         aws_role: ${{ secrets.NONPRD_DEPLOY_ROLE }}
  #         branch_name: ${{ inputs.branch_name }}
  #         container_name: wallet-connect
  #         cluster_name: wallet-connect-${{ inputs.environment }}-cluster
  #         service_name: wallet-connect-${{ inputs.environment }}-service-fargate
  #         spring_application_name: wallet-connect-${{ inputs.environment }}
  #         tag_to_use: version
  #         token: ${{ secrets.VENLY_GITHUB_ACTIONS_TOKEN }}
